# Variables for the root yml configuration
gn_file_pub_rsa_pro: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
gn_file_pub_rsa_dev: "{{ lookup('file', '~/.ssh/id_rsa_deploying.pub') }}" 

# Docker Tasks
dk_name_user: usuario
dk_group_user: usuarios
dk_uid_user: "1010"
dk_gid_user: "1010"
dk_domain: "sudano.net"
# this value it's override in the playbooks of instances
#dk_nc_subdomain: "nc.{{ dk_domain }}" 
dk_config_folder: /{{ dk_name_user }}
dk_app_folder: "{{ dk_config_folder }}/www"
dk_db_folder: "/ncBD"
dk_data_folder: "/ncData"

# Portainer vars
pt_container_name: portainer
pt_data_folder: "/ptData"
pt_host: "172.0.11.4"

# Firewalls variables
fw_ports:
  - 22/tcp
  - 443/tcp
  - 8000/tcp
  - 9000/tcp
  - 9090/tcp
  - 10000/tcp

# LetsEncrypt tasks
le_email: pepitogrillo148@hotmail.com
# le_debug: false

# Nextcloud Tasks
nc_container_name: nextcloud
nc_admin_user: admin
nc_occ_command: "docker exec -it {{ nc_container_name }} sudo -u abc /usr/bin/php /config/www/nextcloud/occ"
# The follow var it's in value
# nc_admin_pass:
nc_nextcloud_host: "172.0.11.2"
# The follow var it's in value
# nc_app_users:
#   - { id: capside, name: Capside, pass: somestring }
#   - { id: test, name: Test, pass: somestring }
nc_app_groups:
  - { id: bookmarks, name: bookmarks }
  - { id: calendar, name: calendars }
  - { id: contacts, name: contacts }
  - { id: tasks, name: tasks }
  - { id: side_menu, name: side_menu }
  - { id: users, name: users }
nc_install_apps:
  - calendar
  - contacts
  - bookmarks
  - tasks
  - side_menu
nc_disable_apps:
  - comments
  - accessibility
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - recommendations
  - photos
  - support
  - survey_client
  - systemtags
  - user_ldap

# MySQL Database
mysql_container_name: mariadb
mysql_db_host: "172.0.11.3"
mysql_db_name: ncdb
mysql_db_user: ncuser
# mysql_db_pass: value in vault

# Network Config
net_name_network: "nextcloud"
net_cidr: 172.0.11.0/16
net_gateway_ip: 172.0.11.1
net_subnet_range: 172.0.11.0/28

# Pip Role
pip_package: python3-pip
pip_install_packages: [ docker, docker-compose ]

# Docker Role
docker_users: [ root, usuario ]
php_version: '7.3'