- name: Tasks for install Webmin
  tags: [ 'webmin' ]
  block:
    - name: Setting the correct interpreter of python 
      set_fact:
        ansible_python_interpreter: "/usr/bin/python"

    - name: Started Firewalld to the instalation of Webmin
      service:
        name: firewalld
        state: started

    - name: Add webmin yum repository
      yum_repository:
        baseurl: 'https://download.webmin.com/download/yum'
        state: present
        gpgcheck: true
        gpgkey: http://www.webmin.com/jcameron-key.asc
        name: webmin
        description: Webmin Yum Repo

    - name: Install Webmin dependencies
      package:
        name: ['perl-Authen-PAM', 'perl-Net-SSLeay', 'openssl', 'perl-IO-Tty', 'perl-Encode-Detect', 'python36-PyMySQL', 'mariadb', 'mariadb-server', 'mariadb-devel', 'perl']
        state: present
        update_cache: true

    - name: Install Webmin in VPS instance
      package:
        name: webmin
        state: present
      notify: 
        - "Stop Webmin"
        - "Restart Webmin"
      when: not ansible_check_mode

    - name: Stop and disable a old Webmin service
      shell: "service webmin stop"

    - name: Disable the old Webmin service
      service: # when I use the module service, webmin service don't be stop
        name: webmin
        state: restarted
        enabled: no
        force: yes
        daemon_reload: yes