- name: Setting by default all config of Nextcloud
  tags: [ 'by_default' ]
  block:
    - name: Setting the correct interpreter of python 
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"
      tags: always

    - name: Delete database of Nextcloud
      mysql_db:
        login_host: "{{ mysql_db_host }}"
        login_user: "{{ mysql_db_user }}"
        login_password: "{{ mysql_db_pass }}"
        name: "{{ mysql_db_name }}"
        state: absent

    - name: Analyzing the Nextcloud directories to delete...
      find:
        paths: [ "{{ dk_data_folder }}" ]
        patterns: [ "appdata_*", "files_*", "{{ item.id }}" ]
        use_regex: true
        file_type: directory
      register: folders_to_delete
      with_items: "{{ nc_app_users }}"

    - name: Deleting the Nextcloud directories...
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ folders_to_delete.files }}"

    - name: Change config of Nextcloud at not installed
      lineinfile:
        dest: "{{ dk_app_folder }}/nextcloud/config/config.php"
        regexp: "'installed' =>"
        line: "'installed' => false,"

    - name: Create a one file of control CAN_INSTALL
      file:
        path: "{{ dk_app_folder }}/nextcloud/config/CAN_INSTALL"
        owner: "{{ dk_name_user }}"
        group: "{{ dk_group_user }}"
        mode: "0640"
        state: touch
