---
- name: Tasks create a network of Docker
  tags: [ 'nextcloud', 'portainer' ]
  block:
    - name: Setting the correct interpreter of python 
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"
      tags: always

    - name: Restart Docker service because some times the service it's blocked
      service:
        name: docker
        state: restarted

    - name: Change config of {{ net_name_network }} network with custom IPAM config
      docker_network:
        name: "{{ net_name_network }}"
        enable_ipv6: no
        ipam_config:
          - subnet: "{{ net_cidr }}"
            gateway: "{{ net_gateway_ip }}"
            iprange: "{{ net_subnet_range }}"