---
- name: Tasks for install NextCloud
  tags: [ 'nextcloud' ]
  block:
    - name: Setting the correct interpreter of python 
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"
    
    - name: Install all the PHP requirements to NextCloud works properly
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - '{{ nc_php_list_prerequisities }}'

    - name: Unarchive the NextCloud file
      unarchive:
        src: "{{ nc_version_url_package }}"
        dest: "{{ dk_nextcloud_folder }}"
        extra_opts: [--strip-components=1]
        remote_src: true

    # - name: Rename the folder where we have Nextcloud
    #   copy:
    #     src: "{{ dk_wserver_folder }}/nextcloud/"
    #     dest: "{{ dk_nextcloud_folder }}"
    #     remote_src: true

    - name: "Set the correct user and group in the NextCloud folder ( {{ dk_nextcloud_folder }} )."
      file:
        path: "{{ dk_nextcloud_folder }}"
        state: directory
        owner: "{{ nx_name_user }}"
        group: "{{ nx_group_user }}"
        recurse: true

    - name: "Set the correct permissions in the NextCloud folder ( {{ dk_nextcloud_folder }} )."
      file:
        path: "{{ dk_nextcloud_folder }}"
        state: directory
        mode: 0775

    - name: "Set the correct permissions in the NextCloud DATA folder ( {{ dk_data_folder }} )."
      file:
        path: "{{ dk_data_folder }}"
        state: directory
        mode: 0770