---
- name: Tasks for config FirewallD
  tags: [ 'firewall' ]
  block:
    - name: Setting the correct interpreter of python 
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"
      tags: always