- name: Setting the correct interpreter of python 
  set_fact:
    ansible_python_interpreter: "/usr/bin/python3"
  tags: always

- name: Check if certificate already exists in source folder.
  stat:
    path: /etc/letsencrypt/live/{{ dk_domain }}/fullchain.pem
  register: letsencrypt_cert_src

- name: Copy certificates at the correct path
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    remote_src: yes
    owner: root
    mode: "0600"
  with_items:
    - { src: "/etc/letsencrypt/live/{{ dk_domain }}/fullchain.pem", dst: "{{ dk_config_folder }}/keys/cert.crt" }
    - { src: "/etc/letsencrypt/live/{{ dk_domain }}/privkey.pem", dst: "{{ dk_config_folder }}/keys/cert.key" }
  when: [ letsencrypt_cert_src.stat.exists == true ]

- name: Copy config nextcloud at the correct path
  template:
    src: autoconfig.php.j2
    dest: "{{ dk_config_folder }}/www/nextcloud/config/autoconfig.php"
    owner: "{{ dk_name_user }}"
    group: "{{ dk_group_user }}"
    force: yes
    mode: "0660"

- name: Restart container Nextcloud
  docker_container:
    name: nextcloud
    restart: yes
    state: started