# Variables for the root yml configuration
gn_file_pub_rsa: ~/.ssh/id_rsa.pub

# Docker Tasks
dk_name_user: usuario
dk_group_user: usuarios
dk_uid_user: "1010"
dk_gid_user: "1010"
dk_domain: "sudano.net"
dk_config_folder: /{{ dk_name_user }}
dk_app_folder: "{{ dk_config_folder }}/www"
dk_db_folder: "/ncBD"
dk_data_folder: /ncData

 # Nextcloud Tasks
nc_email: pepitogrillo148@hotmail.com
nc_admin_user: admin
# nc_admin_pass: value in vault
nc_nextcloud_host: "172.11.0.2"

# MySQL Database
mysql_db_host: "172.11.0.3"
mysql_db_name: ncdb
mysql_db_user: ncuser
# mysql_password: value in vault

# Network Config
net_name_network: "nextcloud"
net_cidr: 172.11.0.0/16
net_gateway_ip: 172.11.0.1
net_subnet_range: 172.11.0.0/28

# Pip Role
pip_package: python3-pip
pip_install_packages: [ docker, docker-compose ]

# Docker Role
docker_users: [ root, usuario ]
php_version: '7.3'