---
- name: Apply base configuration for OVH Instance
  hosts: 
    - all

  become_method: sudo
  become_user: root
  become: true

  tasks: # the order of tasks it's important to the correct execution
    - { name: Backup of MariaDB, include_tasks: "tasks/{{ ansible_distribution }}/backup/mariadb.yml", tags: [ 'never', 'backup' ]}
    - { name: Backup of NextCloud, include_tasks: "tasks/{{ ansible_distribution }}/backup/nextcloud.yml", tags: [ 'never', 'backup' ]}
