---
- name: Apply base configuration for Google instance
  hosts: 
    - all
  
  become_method: sudo
  become_user: root
  become: true

  roles:
    - { role: geerlingguy.repo-epel, become: yes, tags: [ 'epel' ], when: ansible_os_family == 'RedHat' }
    - { role: geerlingguy.pip, tags: [ 'pip', 'nextcloud', 'portainer' ], when: ansible_os_family == 'RedHat' }
    - { role: geerlingguy.docker, check_mode: no, tags: [ 'nextcloud', 'portainer' ] }

  tasks: # the order of tasks it's important to the correct execution
    - { name: FirewallD Configuration, include_tasks: "tasks/{{ ansible_distribution }}/config/firewalld.yml", tags: [ 'firewall' ]}       
    - { name: Docker network installation, include_tasks: "tasks/{{ ansible_distribution }}/install/network.yml", tags: [ 'nextcloud', 'portainer' ] }
    - { name: Webmin Installation, include_tasks: "tasks/{{ ansible_distribution }}/install/webmin.yml", tags: [ 'webmin' ] }
    - { name: Nextcloud Installation, include_tasks: "tasks/{{ ansible_distribution }}/install/nextcloud.yml", tags: [ 'nextcloud' ] }
    - { name: LetsEncrypt Settings, include_tasks: "tasks/{{ ansible_distribution }}/config/letsencrypt.yml", tags: [ 'letsencrypt' ] }
    - { name: Nextcloud Settings, include_tasks: "tasks/{{ ansible_distribution }}/config/nextcloud.yml", tags: [ 'nextcloud' ] }
    - { name: Webmin Settings, include_tasks: "tasks/{{ ansible_distribution }}/config/webmin.yml", tags: [ 'webmin' ] }