---
collections:
  - name: jgoutin.home
    version: "2.0.1"
roles:
  - name: geerlingguy.repo-epel
    version: "3.1.1"

  - name: geerlingguy.firewall
    version: "2.5.0"

  - name: geerlingguy.ansible
    version: "2.1.0"

  - name: geerlingguy.pip
    version: "2.2.0"

  - name: geerlingguy.repo-remi
    version: "2.0.1"

  # - name: geerlingguy.php
  #   version: "4.8.0"
    
  - name: geerlingguy.php-versions
    version: "5.0.0"

  - name: geerlingguy.php-mysql
    version: "2.1.0"

  - name: geerlingguy.nginx
    version: "3.1.3"
  
  - name: geerlingguy.certbot
    version: "5.0.1"
  
  - name: geerlingguy.docker
    version: "2.7.0"

  - name: geerlingguy.mysql
    version: "4.1.0"