---
- name: Apply base configuration for OVH Instance
  hosts: 
    - all

  become_method: sudo
  become_user: root
  become: true

  tasks: # the order of tasks it's important to the correct execution
    - { name: Playbook to clean VPS instance, include_tasks: "tasks/Tools/clean.yml", tags: [ 'never', 'clean', 'clean_my_data' ] }
    - { name: Reset by default a Nextcloud Instalation, include_tasks: "tasks/Tools/by_default.yml", tags: [ 'never', 'by_default' ] }
    - { name: Production Settings, include_tasks: "tasks/Tools/production.yml", tags: [ 'never', 'production' ] }
